"""
SQLAlchemy ORM entity definitions for Chronos Stadium AI.

Each class maps to a PostgreSQL table and represents a core domain
object in the stadium operations system.  All tables use
``server_default=func.now()`` for timestamp columns so the database
is the single source of truth for record creation times.
"""
from sqlalchemy import Boolean, Column, DateTime, Float, ForeignKey, Integer, JSON, String
from sqlalchemy.sql import func

from app.database.session import Base


class User(Base):
    """Registered operator user account.

    Attributes:
        id: Auto-incremented primary key.
        email: Unique, indexed email address used for authentication.
        hashed_password: Bcrypt-hashed password — the plaintext is never stored.
        role: Coarse-grained permission role (e.g. ``operator``, ``admin``).
        created_at: UTC timestamp set by the database on record creation.
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    email = Column(String, unique=True, index=True, nullable=False)
    hashed_password = Column(String, nullable=False)
    role = Column(String, default="operator", nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)


class SensorData(Base):
    """Raw telemetry reading from a stadium sensor.

    Each row represents a single point-in-time observation from one
    physical or virtual sensor (e.g. crowd counter, weather station).

    Attributes:
        id: Auto-incremented primary key.
        sensor_type: Category of sensor (``crowd``, ``weather``, ``transit``,
            ``food``, ``energy``).
        location: Human-readable location label (e.g. ``Gate A``).
        value: The numeric reading (units depend on ``sensor_type``).
        metadata_json: Arbitrary key-value pairs for extended sensor metadata.
        timestamp: UTC timestamp of the observation.
    """

    __tablename__ = "sensor_data"

    id = Column(Integer, primary_key=True, index=True)
    sensor_type = Column(String, index=True, nullable=False)
    location = Column(String, index=True, nullable=False)
    value = Column(Float, nullable=False)
    metadata_json = Column(JSON, default=dict)
    timestamp = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)


class Incident(Base):
    """An operational incident that requires staff attention.

    Incidents are raised by the AI engine or manually by operators and
    progress through a lifecycle: ``active`` → ``resolved``.

    Attributes:
        id: Auto-incremented primary key.
        title: Short summary of the incident (required).
        description: Optional detailed narrative.
        severity: One of ``low``, ``medium``, ``high``, ``critical``.
        status: Lifecycle state — ``active`` or ``resolved``.
        location: Where in the stadium the incident occurred.
        created_at: UTC timestamp set by the database on record creation.
        resolved_at: UTC timestamp when the incident was closed (nullable).
    """

    __tablename__ = "incidents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, nullable=False)
    description = Column(String, nullable=True)
    severity = Column(String, nullable=False)  # low | medium | high | critical
    status = Column(String, default="active", nullable=False)  # active | resolved
    location = Column(String, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    resolved_at = Column(DateTime(timezone=True), nullable=True)


class FuturePrediction(Base):
    """A single simulated future generated by the AI engine.

    Groups of predictions sharing the same ``scenario_id`` represent the
    full set of ranked futures from one simulation run.

    Attributes:
        id: Auto-incremented primary key.
        scenario_id: UUID or slug linking this prediction to its parent run.
        probability: Estimated probability (0-100) that this future occurs.
        risk_score: Composite risk score (0-10) from the risk calculator.
        description: Human-readable narrative of this simulated timeline.
        timeline_events: Ordered list of expected operational events.
        operational_impact: Qualitative severity label (e.g. ``Severe``).
        recommended_decision: The highest-priority recommended action.
        created_at: UTC timestamp set by the database on record creation.
    """

    __tablename__ = "future_predictions"

    id = Column(Integer, primary_key=True, index=True)
    scenario_id = Column(String, index=True, nullable=False)
    probability = Column(Float, nullable=False)
    risk_score = Column(Float, nullable=False)
    description = Column(String, nullable=False)
    timeline_events = Column(JSON, default=list)
    operational_impact = Column(String, nullable=False)
    recommended_decision = Column(String, nullable=False)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
